name: uix_todomvc_persistent
version: 0.0.1
description: An absolute bare-bones web app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  uix:
    git: git://github.com/localvoid/uix.git
  route_hierarchical: any
  vacuum_persistent: any
